# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'taxi_rides_ny'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'Analytics'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["Step4-Analytics-Eng/dbt/models"]
analysis-paths: ["Step4-Analytics-Eng/dbt/analysis"]
test-paths: ["Step4-Analytics-Eng/dbt/tests"]
seed-paths: ["Step4-Analytics-Eng/dbt/seeds"]
macro-paths: ["Step4-Analytics-Eng/dbt/macros"]
snapshot-paths: ["Step4-Analytics-Eng/dbt/snapshots"]

target-path: "Step4-Analytics-Eng/dbt/target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "Step4-Analytics-Eng/dbt/target"
    - "Step4-Analytics-Eng/dbt/dbt_packages"
    - "Step4-Analytics-Eng/dbt/dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  taxi_rides_ny:
      # Applies to all files under models/.../
      staging:
          materialized: view
      core:
          materialized: table
vars:
  payment_type_values: [1, 2, 3, 4, 5, 6]

seeds: 
    taxi_rides_ny:
        taxi_zone_lookup:
            +column_types:
                locationid: numeric